
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 12345
    driveer-class-name: org.postgresql.Driver
  jpa:

    properties.hibernate:
      show_sql: true
      format_sql: true
      ddl-auto: update

